#!/bin/sh
if [ "$(uname -s)" == "Linux" ]; then
	make -s install UNOPKG_PREFIX=$HOME/git/libreoffice/lo43/opt/libreoffice4.3/program/
elif [ "$(uname -s)" == "Darwin" ]; then
	make -s install UNOPKG_PREFIX=/Applications/LibreOffice.app/Contents/MacOS/
else
	make -s install UNOPKG_PREFIX="/cygdrive/c/Program Files/LibreOffice 4/program/"
fi
