= ged2dot, a GEDCOM to Graphviz converter

== What's the problem the tool solves?

`ged2dot` is a script that takes a http://en.wikipedia.org/wiki/GEDCOM[GEDCOM]
file and tries to visualize it using http://www.graphviz.org/[Graphviz]'s `dot`
tool. The basic idea is that you can map individuals to graph nodes and
families to graph edges, then `dot` takes care of the rest. What's unique about
`ged2dot` is that it allows more than showing ancestors and descendants of a
single individual (what you can easily do with random family editor software).

== Scenarios

Currently it allows to show a ancestors of a family (both husband and wife),
and you can set how many generations do you want to see, and also for how many
generations you want to include sibling families as well -- but it can be
easily extended to support other scenarios as well.

Icons are from
http://www.wpzoom.com/wpzoom/new-freebie-wpzoom-developer-icon-set-154-free-icons/[WPZOOM],
in case placeholders have to be used for missing images.
